config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Lista todas as tasks
  get 'tasks', to: 'tasks#index'

  # Mostra um form para criar uma nova task
  get 'tasks/new', to: 'tasks#new', as: :new_task

  # Mostra uma das tasks
  get 'tasks/:id', to: 'tasks#show', as: :task

  # Cria uma nova task
  post 'tasks', to: 'tasks#create'

  # Mostra um form para o user editar a tarefa
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task

  # Atualiza a task
  patch 'tasks/:id', to: 'tasks#update'

  # Deleta uma task
  delete 'tasks/:id', to: 'tasks#destroy', as: :delete

  # resources :tasks
  # resources :tasks, except: [:edit, :update]
  # resources :tasks, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :task_find, only: %i[show edit update destroy]

  def index
    @tasks = Task.all
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit; end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_find
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for(task) do |f| %>
  <div class="form-group col-md-3">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group col-md-3">
    <%= f.label :details %>
    <%= f.text_field :details, class: "form-control" %>
  </div>
  <div class="form-group col-md-3">
    <%= f.label :task %>
    <%= f.input :completed, :as => :boolean, class: "form-control" %>
  </div>
  
  <%= link_to "Cancel", tasks_path , class: "btn btn-danger rounded ml-3" %>
  <%= f.submit class: "btn btn-primary rounded ml-3" %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<% @tasks.each do |task| %>
  <% if task.completed %>
    <input type="checkbox" checked>
    <label> <%= link_to task.title, task_path(task) %> <%= link_to "🗑️", delete_path(task), method: :delete, data: { confirm: "Are you sure?" } %> </label><br>
  <% else %>
    <input type="checkbox" >
    <label> <%= link_to task.title, task_path(task) %> <%= link_to "🗑️", delete_path(task), method: :delete, data: { confirm: "Are you sure?" } %> </label><br>
  <% end %>
<% end %>

<hr><br>

<%= link_to "+ Add a new task", new_task_path %>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<div class="row">
  <div class="col-5">
    <h1> <%= @task.title %> </h1>
  </div>
  <div class="col-2 ml-3">
    <%= link_to "Edit this task", edit_task_path(@task), class: "btn btn-secondary" %> 
  </div>
</div>
<div class="row">
  <div class="col-6">
    <div class="viewTaskDetails">
      <%= @task.details %>
    </div> 
  </div>
</div>

<br>

<%= @task.completed ? '<input type="checkbox" checked>'.html_safe : '<input type="checkbox">'.html_safe %>
<%= @task.completed ? '<label> This task is completed! </label><br>'.html_safe : '<label> This task is not completed yet! </label><br>'.html_safe %>

<hr><br>

<%= link_to "Back to list", tasks_path %>